# Generated by Django 4.2.7 on 2025-01-26 01:07

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('budget_id', models.AutoField(primary_key=True, serialize=False)),
                ('origem', models.CharField(blank=True, max_length=255, null=True)),
                ('prazo', models.DateField()),
                ('comprovante_pagamento', models.FileField(null=True, upload_to='comprovantes/')),
                ('forma_de_pagamento', models.CharField(blank=True, choices=[('A VISTA', 'A vista'), ('FATURADO', 'Faturado')], max_length=255, null=True)),
                ('quantidade_de_documentos', models.IntegerField()),
                ('numero_de_parcelas', models.IntegerField(blank=True, null=True)),
                ('valor_de_entrada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_restante', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_segunda_parcela', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('arquivado', models.BooleanField(default=False)),
                ('numero_ca', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('ORCAMENTO', 'Orçamento'), ('EM ANDAMENTO', 'Em Andamento'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='ORCAMENTO', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_do_representante', models.CharField(max_length=255, null=True)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=55)),
                ('tipo_do_cliente', models.CharField(choices=[('CLIENTE A VISTA', 'Cliente a vista'), ('MENSALISTA', 'Mensalista')], max_length=50)),
                ('cpf_cnpj', models.CharField(max_length=255, null=True)),
                ('endereco', models.CharField(max_length=255, null=True)),
                ('cidade', models.CharField(max_length=255, null=True)),
                ('estado', models.CharField(max_length=255, null=True)),
                ('cep', models.CharField(max_length=255, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('familia_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_da_familia', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('vendedor_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceModalities',
            fields=[
                ('modalidade_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('prazo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Translator',
            fields=[
                ('tradutor_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('prazo_em_dias', models.IntegerField(default=1)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceDocument',
            fields=[
                ('servico_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_servico', models.CharField(choices=[('APOSTILAMENTO', 'Apostilamento'), ('POSTAGEMENVIO', 'Postagem/Envio')], max_length=255)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('quantidade', models.IntegerField(blank=True, default=1, null=True)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos_documentos', to='dados.budget')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('servico_id', models.AutoField(primary_key=True, serialize=False)),
                ('ordem_de_servico', models.CharField(max_length=255)),
                ('data_entrada', models.DateField()),
                ('data_envio', models.DateField()),
                ('modalidade', models.CharField(choices=[('NORMAL', 'Normal'), ('EXPRESSO', 'Expresso')], max_length=255)),
                ('status', models.CharField(choices=[('ETAPA 1', 'Entrada de Serviço'), ('ETAPA 2', 'Assinatura do Tradutor'), ('ETAPA 3', 'Entrada do Tradutor'), ('ETAPA 4', 'Entrada Cartório')], max_length=255, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cliente', to='dados.customer')),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FamiliaServiço', to='dados.family')),
                ('tradutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tradutor', to='dados.translator')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsibleTax',
            fields=[
                ('responsavel_fiscal_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=55)),
                ('cpf_cnpj', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ResponsavelFiscal', to='dados.budget')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('documento_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('tipo_documento', models.CharField(choices=[('CRC', 'CRC'), ('TRADUCAO', 'Tradução')], max_length=255, null=True)),
                ('descricao', models.CharField(max_length=255)),
                ('idioma_da_traducao', models.CharField(choices=[('INGLES', 'Inglês'), ('ESPANHOL', 'Espanhol'), ('FRANCES', 'Francês'), ('ALEMAO', 'Alemão'), ('ITALIANO', 'Italiano')], max_length=255, null=True)),
                ('tipo_de_assinatura', models.CharField(blank=True, default='N/A', max_length=255, null=True)),
                ('quantidade', models.IntegerField(blank=True, default=1, null=True)),
                ('data_devolucao', models.DateField(blank=True, null=True)),
                ('data_entrada_tradutor', models.DateField(blank=True, null=True)),
                ('data_envio_tradutor', models.DateField(blank=True, null=True)),
                ('data_devolucao_tradutor', models.DateField(blank=True, null=True)),
                ('finalizacao', models.CharField(blank=True, max_length=255, null=True)),
                ('data_envio_cartorio', models.DateField(blank=True, null=True)),
                ('modalidade', models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('EXPRESSO', 'Expresso')], max_length=255, null=True)),
                ('prazo', models.DateField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista_documentos', to='dados.budget')),
                ('tradutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TradutorDocument', to='dados.translator')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='nome_da_familia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Familia', to='dados.family'),
        ),
        migrations.AddField(
            model_name='budget',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ClienteOrcamento', to='dados.customer'),
        ),
        migrations.AddField(
            model_name='budget',
            name='documentos',
            field=models.ManyToManyField(related_name='DocumentosBudget', to='dados.document'),
        ),
        migrations.AddField(
            model_name='budget',
            name='familia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FamiliaOrcamento', to='dados.family'),
        ),
        migrations.AddField(
            model_name='budget',
            name='responsaveis_fiscais',
            field=models.ManyToManyField(related_name='ResponsaveisFiscaisBudget', to='dados.responsibletax'),
        ),
        migrations.AddField(
            model_name='budget',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Vendedor', to='dados.seller'),
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('cliente', 'Cliente'), ('colaborador', 'Colaborador'), ('vendedor', 'Vendedor'), ('financeiro', 'Financeiro'), ('gerencia', 'Gerência')], default='cliente', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
