# Generated by Django 4.2.7 on 2025-01-26 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0003_remove_customer_nome_da_familia_alter_customer_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioOrcamento', to=settings.AUTH_USER_MODEL),
        ),
    ]
