# Generated by Django 4.2.7 on 2025-02-16 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0004_budget_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='status',
            field=models.CharField(blank=True, choices=[('ORCAMENTO', 'Orçamento'), ('EM ANDAMENTO', 'Em Andamento'), ('PENDENTE', 'Pendente'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='ORCAMENTO', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comentario_id', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.TextField()),
                ('data', models.DateField(auto_now_add=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comentarios', to='dados.budget')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioComentario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
