# Generated by Django 4.2.7 on 2025-02-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0005_alter_budget_status_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
