# Generated by Django 4.2.7 on 2025-02-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0006_alter_comment_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaAzulToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=255)),
                ('refresh_token', models.CharField(max_length=255)),
                ('expires_in', models.DateTimeField()),
            ],
        ),
    ]
