# Generated by Django 4.2.7 on 2025-03-17 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0007_contaazultoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='id_conta_azul',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
