# Generated by Django 4.2.7 on 2025-03-20 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0008_seller_id_conta_azul'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioVendedor', to=settings.AUTH_USER_MODEL),
        ),
    ]
