# Generated by Django 4.2.7 on 2025-06-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0010_alter_budget_comprovante_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contaazultoken',
            name='access_token',
            field=models.TextField(max_length=2550),
        ),
        migrations.AlterField(
            model_name='contaazultoken',
            name='refresh_token',
            field=models.TextField(max_length=2550),
        ),
    ]
